#!/usr/bin/env python3
"""Rebuild CUMR MJCF adapters from the bundled, unmodified TienKung sources.

Run with the CUMR Python environment (MuJoCo 3.3.7, numpy and trimesh).
See README.md and LICENSE in this directory for provenance and modifications.
"""
from pathlib import Path
import tempfile
import xml.etree.ElementTree as ET

import mujoco
import numpy as np
import trimesh

ROOT = Path(__file__).resolve().parent
NOTICE = (
    "Modified for CUMR: generated by assets/tienkung/rebuild_models.py. "
    "See ../README.md for modifications, upstream revision and ../LICENSE."
)


def write_xml(root, path):
    ET.indent(root, space="  ")
    ET.ElementTree(root).write(path, encoding="utf-8", xml_declaration=True)


def restore_pelvis_inertia(root, urdf):
    # The upstream 2-series MJCF omits pelvis inertia, so MuJoCo otherwise
    # infers an excessive mass from duplicate visual/collision mesh volumes.
    source = urdf.find("./link[@name='pelvis']/inertial")
    origin = source.find("origin")
    inertia = source.find("inertia")
    if not np.allclose(np.fromstring(origin.get("rpy", "0 0 0"), sep=" "), 0):
        raise ValueError("Pelvis inertia requires a rotated URDF frame")
    pelvis = root.find("./worldbody/body[@name='pelvis']")
    ET.SubElement(
        pelvis, "inertial", pos=origin.get("xyz"),
        mass=source.find("mass").get("value"),
        fullinertia=" ".join(inertia.get(k) for k in ("ixx", "iyy", "izz", "ixy", "ixz", "iyz")),
    )


def adapt_native(name, urdf_name):
    directory = ROOT / name
    root = ET.parse(directory / "source.xml").getroot()
    root.insert(0, ET.Comment(NOTICE))
    # Upstream references this default material without defining it.
    root.find("./default/default/default[@class='visual']/geom").set("material", "default_material")
    urdf = ET.parse(directory / "urdf" / urdf_name).getroot()
    restore_pelvis_inertia(root, urdf)
    # The Dex torque XML allows several joints beyond its URDF limits.
    # Retarget within both published sets of limits.
    for joint in urdf.findall("joint[@type='revolute']"):
        target = root.find(f".//joint[@name='{joint.get('name')}']")
        lower, upper = np.fromstring(target.get("range"), sep=" ")
        limits = joint.find("limit")
        lower = max(lower, float(limits.get("lower")))
        upper = min(upper, float(limits.get("upper")))
        target.set("range", f"{lower:.16g} {upper:.16g}")
    path = directory / "model.xml"
    write_xml(root, path)
    return path


def convert_tiangong3():
    directory = ROOT / "tiangong3"
    urdf = ET.parse(directory / "urdf/tiangong3.urdf").getroot()
    converted = set()
    # Binary STL has a 200000-face limit in MuJoCo. OBJ retains every triangle
    # and vertex coordinate, without decimating the exterior used by CUMR.
    for mesh in urdf.findall(".//mesh"):
        path = directory / "meshes" / Path(mesh.get("filename")).name
        with path.open("rb") as stream:
            header = stream.read(84)
        if int.from_bytes(header[80:84], "little") > 200000:
            obj = path.with_suffix(".obj")
            if obj not in converted:
                surface = trimesh.load_mesh(path, process=False)
                surface.merge_vertices()
                surface.export(obj, file_type="obj", digits=9, include_color=False)
                converted.add(obj)
            path = obj
        mesh.set("filename", path.name)
    extension = ET.SubElement(urdf, "mujoco")
    ET.SubElement(extension, "compiler", meshdir=str(directory / "meshes"),
                  discardvisual="false", fusestatic="false")
    with tempfile.TemporaryDirectory(prefix="umr-tiangong3-") as temp:
        input_path = Path(temp) / "model.urdf"
        output_path = Path(temp) / "model.xml"
        write_xml(urdf, input_path)
        model = mujoco.MjModel.from_xml_path(str(input_path))
        mujoco.mj_saveLastXML(str(output_path), model)
        root = ET.parse(output_path).getroot()
    root.insert(0, ET.Comment(NOTICE))
    root.find("compiler").set("meshdir", "meshes")
    for mesh in root.findall("./asset/mesh"):
        mesh.set("file", Path(mesh.get("file")).name)
    pelvis = root.find("./worldbody/body[@name='pelvis']")
    ET.SubElement(pelvis, "freejoint", name="floating_base")
    for body in root.findall(".//body"):
        for geom in body.findall("geom"):
            visual = geom.get("contype") == "0" and geom.get("conaffinity") == "0"
            kind = "visual" if visual else "collision"
            geom.set("name", f"{body.get('name')}_{kind}")
            geom.set("group", "2" if visual else "1")
            if not visual:
                geom.set("friction", "1 0.01 0.01")
    motors = ET.SubElement(root, "actuator")
    for joint in urdf.findall("joint"):
        if joint.get("type") != "revolute":
            continue
        effort = float(joint.find("limit").get("effort"))
        ET.SubElement(motors, "motor", name=joint.get("name"), joint=joint.get("name"),
                      ctrllimited="true", ctrlrange=f"{-effort:g} {effort:g}")
    ET.SubElement(root.find("worldbody"), "geom", name="floor", type="plane",
                  size="10 10 0.1", rgba="0.8 0.8 0.8 1", friction="1 0.005 0.0001")
    path = directory / "model.xml"
    write_xml(root, path)
    return path


def align_soles_to_ground(path):
    # Place the lowest sole vertex on z=0 in the default standing pose.
    parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))
    root = ET.parse(path, parser=parser).getroot()
    pelvis = root.find("./worldbody/body[@name='pelvis']")
    model = mujoco.MjModel.from_xml_path(str(path))
    data = mujoco.MjData(model)
    mujoco.mj_forward(model, data)
    lowest = []
    for side in ("l", "r"):
        geom_id = model.geom(f"ankle_roll_{side}_link_visual").id
        mesh_id = model.geom_dataid[geom_id]
        start = model.mesh_vertadr[mesh_id]
        vertices = model.mesh_vert[start:start + model.mesh_vertnum[mesh_id]]
        world = vertices @ data.geom_xmat[geom_id].reshape(3, 3).T + data.geom_xpos[geom_id]
        lowest.append(world[:, 2].min())
    pos = np.fromstring(pelvis.get("pos", "0 0 0"), sep=" ")
    pos[2] -= min(lowest)
    pelvis.set("pos", " ".join(f"{v:.10f}" for v in pos))
    write_xml(root, path)


def main():
    paths = [adapt_native("tiangong2dex", "tiangong2dex.urdf"),
             adapt_native("tiangong2pro", "tiangong2.0_pro_urdf.urdf"),
             convert_tiangong3()]
    for path in paths:
        align_soles_to_ground(path)
        model = mujoco.MjModel.from_xml_path(str(path))
        print(f"{path.parent.name}: {model.nv - 6} joints, nq={model.nq}, "
              f"{model.nmesh} meshes, mass={model.body_mass.sum():.3f} kg")


if __name__ == "__main__":
    main()
